INSERT INTO POSTS (USER_ID, BODY)
VALUES (1, "First post");

INSERT INTO POSTS (USER_ID, BODY)
VALUES (2, "Second post");

INSERT INTO POSTS (USER_ID, BODY)
VALUES (3, "Third post");

COMMIT;

SELECT * FROM POSTS;

UPDATE POSTS
SET BODY = "To delete"
WHERE BODY = "Second post";

COMMIT;

SELECT * FROM POSTS;

DELETE FROM POSTS
WHERE BODY = "To delete";

COMMIT;