SELECT I.SUMMARY, L.NAME
FROM ISSUESLIST L
JOIN ISSUES I ON L.ID = I.ISSUESLIST_ID;

SELECT I.SUMMARY, U.FIRSTNAME, U.LASTNAME
FROM USERS U
JOIN ISSUES I ON U.ID = I.USER_ID_ASSIGNEDTO;

SELECT U.FIRSTNAME, U.LASTNAME, COUNT(*) AS ISSUES_NUMBER
FROM ISSUES I
JOIN USERS U ON U.ID = I.USER_ID_ASSIGNEDTO
GROUP BY I.USER_ID_ASSIGNEDTO;